controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_controllers:
    resource: '../src/Controller/Api/'
    type: attribute
    prefix: /api
api_admin:
    resource: '../src/Controller/Api/Admin/'
    type: attribute
    prefix: /api/admin
api_login_check:
    path: /api/login_check
api_refresh_token:
    path: /api/token/refresh