name: 'oddsportal-prod'

services:
  db:
    image: mysql:8.0.33
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db_app:/var/lib/mysql"
    env_file:
      - ../.env.prod.local
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - symfony_app

  php:
    build:
      context: ../ # ✅ Zmień kontekst na główny katalog projektu
      dockerfile: .docker/php/Dockerfile.prod # ✅ Podaj pełną ścieżkę do Dockerfile od nowego kontekstu
      args:
        TIMEZONE: ${TIMEZONE}
    networks:
      - symfony_app
    env_file:
      - ../.env.prod.local
    volumes:
      - ../:/var/www/symfony

  nginx:
    build:
      context: ./nginx
    volumes_from:
      - php:ro
    ports:
      - "8080:80" # <-- Wystawiamy na porcie 8080, aby nie kolidował z Nginxem na hoście
    networks:
      - symfony_app
    env_file:
      - ../.env.prod.local
    depends_on:
      - php
  redis:
    image: redis:7.0.0
    networks:
      - symfony_app

volumes:
  db_app:

networks:
  symfony_app: