version: '3.8'
name: 'oddsportal-prod'

services:
  db:
    image: mysql:8.0.33
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db_app:/var/lib/mysql"
    env_file:
      - ../.env.prod.local
    networks:
      - symfony_app

  php:
    build:
      context: ../
      dockerfile: .docker/php/Dockerfile.prod
      args:
        TIMEZONE: ${TIMEZONE}
    env_file:
      - ../.env.prod.local
    # ✅ USUWAMY wolumin montujący kod z hosta! Obraz jest teraz samowystarczalny.
    networks:
      - symfony_app

  nginx:
    build:
      context: ./nginx # Zmieniamy kontekst na główny katalog, aby miał dostęp do plików
    ports:
      - "8080:80"
    env_file:
      - ../.env.prod.local # Ścieżka z głównego katalogu
    networks:
      - symfony_app
    depends_on:
      - php

  redis:
    image: redis:7.0.0
    networks:
      - symfony_app

volumes:
  db_app:

networks:
  symfony_app: