version: '3.8'
name: 'oddsportal-prod'

services:
  db:
    image: mysql:8.0.33
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db_app:/var/lib/mysql"
    env_file:
      - ../.env.prod.local
    networks:
      - symfony_app

  php:
    build:
      context: ../
      dockerfile: .docker/php/Dockerfile.prod
    # ✅ Nadajemy naszemu budowanemu obrazowi stałą nazwę, aby móc się do niego odwołać
    image: oddsportal-php:latest 
    env_file:
      - ../.env.prod.local
    networks:
      - symfony_app

  nginx:
    build:
      context: ../ 
      dockerfile: .docker/nginx/Dockerfile.prod
      # ✅ Przekazujemy nazwę zbudowanego obrazu PHP jako argument do Dockerfile Nginx
      args:
        PHP_IMAGE_WITH_CODE: oddsportal-php:latest
    ports:
      - "8080:80"
    env_file:
      - ../.env.prod.local
    networks:
      - symfony_app
    # ✅ Ta dyrektywa jest teraz BARDZO ważna - Nginx musi być budowany PO PHP
    depends_on:
      - php

  redis:
    image: redis:7.0.0
    networks:
      - symfony_app

volumes:
  db_app: # Zostaje tylko wolumin na dane bazy danych

networks:
  symfony_app: