version: '3.8'
name: 'oddsportal-prod'

services:
  db:
    image: mysql:8.0.33
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db_app:/var/lib/mysql"
    env_file:
      - ../.env.prod.local
    networks:
      - symfony_app

   
  php:
    build:
      context: ../
      dockerfile: .docker/php/Dockerfile.prod
    volumes:
      # ✅ Montujemy nazwany wolumin do katalogu z kodem.
      # Docker najpierw wypełni ten wolumin zawartością z obrazu.
      - app_code:/var/www/symfony
    env_file:
      - ../.env.prod.local
    networks:
      - symfony_app

  nginx:
    build:
      context: ../ # Zmień kontekst, aby miał dostęp do plików konfiguracyjnych
      dockerfile: .docker/nginx/Dockerfile.prod # Użyj dedykowanego pliku
    ports:
      - "8080:80"
    volumes:
      # ✅ Montujemy TEN SAM nazwany wolumin co w PHP, w trybie tylko do odczytu.
      # Dzięki temu Nginx widzi dokładnie te same pliki, co PHP.
      - app_code:/var/www/symfony:ro
    env_file:
      - ../.env.prod.local
    networks:
      - symfony_app
    depends_on:
      - php

  redis:
    image: redis:7.0.0
    networks:
      - symfony_app

volumes:
  db_app:
  app_code:

networks:
  symfony_app: