name: 'oddsportal-prod'

services:
  db:
    image: mysql:8.0.33
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db_app:/var/lib/mysql"
    env_file:
      - ../.env.prod.local
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - symfony_app
  php:
    build:
      context: ../
      dockerfile: .docker/php/Dockerfile.prod
      args:
        TIMEZONE: ${TIMEZONE}
    env_file:
      - ../.env.prod.local
    # ✅ Definiujemy wolumin dla kodu, który będzie współdzielony
    volumes:
      - ../:/var/www/symfony
    networks:
      - symfony_app
  nginx:
    build:
      context: ./nginx
    # ✅ Ta dyrektywa sprawia, że Nginx "widzi" dokładnie te same pliki co PHP
    volumes_from:
      - php:ro
    ports:
      - "8080:80"
    env_file:
      - ./.docker/.env.nginx.local
    networks:
      - symfony_app
    depends_on:
      - php
  redis:
    image: redis:7.0.0
    networks:
      - symfony_app

volumes:
  db_app:

networks:
  symfony_app: