version: '3.8'
name: 'oddsportal-prod'

services:
  db:
    image: mysql:8.0.33
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db_app:/var/lib/mysql"
    env_file:
      - ../.env.prod.local
    networks:
      - symfony_app

  php:
    # ✅ Zamiast sekcji 'build:', używamy 'image:'
    image: temartien/oddsportal-php:latest
    env_file:
      - ../.env.prod.local
    networks:
      - symfony_app

  nginx:
     # ✅ Zamiast sekcji 'build:', używamy 'image:'
    image: temartien/oddsportal-nginx:latest
    ports:
      - "8080:80"
    env_file:
      - ../.env.prod.local
    networks:
      - symfony_app
    depends_on:
      - php

  redis:
    image: redis:7.0.0
    networks:
      - symfony_app

volumes:
  db_app: # Zostaje tylko wolumin na dane bazy danych

networks:
  symfony_app: