name: Deploy to Production

# Uruchom ten workflow przy każdym pushu do gałęzi 'main'
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest # Ten proces będzie działał na wirtualnej maszynie z Ubuntu

    steps:
      # Krok 1: Pobierz kod źródłowy z Twojego repozytorium
      - name: Checkout code
        uses: actions/checkout@v4

      # Krok 2: Skonfiguruj Docker Buildx (nowoczesny builder)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Krok 3: Zaloguj się do Docker Hub używając sekretów
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Krok 4: Zbuduj i wypchnij obraz PHP do Docker Hub
      - name: Build and push PHP image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .docker/php/Dockerfile.prod
          push: true
          # Zastąp 'twoj-login-dockerhub' swoim loginem!
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/oddsportal-php:latest

      # Krok 5: Zbuduj i wypchnij obraz Nginx do Docker Hub
      - name: Build and push Nginx image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .docker/nginx/Dockerfile.prod
          push: true
          # Przekaż nazwę obrazu PHP jako argument do budowania Nginx
          build-args: |
            PHP_IMAGE_WITH_CODE=${{ secrets.DOCKERHUB_USERNAME }}/oddsportal-php:latest
          # Zastąp 'twoj-login-dockerhub' swoim loginem!
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/oddsportal-nginx:latest
          
      # Krok 6: Połącz się z EC2 przez SSH i wykonaj komendy wdrożeniowe
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Przejdź do katalogu z aplikacją
            cd /home/ec2-user/oddsportal

            # Zatrzymaj stare kontenery
            docker compose -f .docker/docker-compose.prod.yml down

            # Pobierz najnowsze obrazy z Docker Hub
            docker compose -f .docker/docker-compose.prod.yml pull

            # Uruchom nowe kontenery
            docker compose -f .docker/docker-compose.prod.yml up -d --force-recreate --remove-orphans

            # Uruchom migracje bazy danych
            docker compose -f .docker/docker-compose.prod.yml exec --user www-data php php bin/console cache:clear --env=prod
            docker compose -f .docker/docker-compose.prod.yml exec --user www-data php php bin/console doctrine:migrations:migrate --env=prod --no-interaction

            # Wyczyść stare, nieużywane obrazy, aby oszczędzać miejsce na dysku
            docker image prune -a -f
